version: '3'

services:
  mysql-standalone:
    image: mysql:5.7
    container_name: mysql-standalone
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile

    depends_on:
      - mysql-standalone